---
title: "FAQ"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FAQ}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## 1. What's the difference between Binder and MyBinder?

mybinder.org is a hosted instance ([aka a BinderHub](https://binderhub.readthedocs.io/en/latest/)) of an open source project called Binder. It so happens that mybinder.org is also hosted by the Binder community. People often use Binder and mybinder.org interchangeably but that's not correct.  There are [several other BinderHubs](https://blog.jupyter.org/binderhub-is-out-of-beta-fa2781a229d6) and more are likely to be available. For more information see [the binder project FAQ](https://mybinder.readthedocs.io/en/latest/faq.html).

## 2. What happens if mybinder goes away?

You can just use the `hub` argument in various functions (`generate_badge`, `build_binder`) and swap out to another binder hub. If your org has the resources (funds + dev ops people), you can even [host your own BinderHub](https://binderhub.readthedocs.io/en/latest/) that has more resources than the public BinderHub.

## 3. What happens if all the public binder hubs go away?

All is not lost. The effort you put into creating a description and Dockerfile will make it easy for people to spin up a Docker instance locally on their machines. It's not as slick but still better than leaving your setup less documented.
 
