test_that("Write installer works", {
  library(glue)
  x <- tempdir(check = TRUE)
  message(glue("Path for tempdir is {x}"))
  fs::dir_create(glue("{x}/.binder"))
  z <- glue::glue("
            library(curl)
            library(fs)
            library(here)
            fs::dir_exists('.')
            ")
  fileConn <- file(glue("{x}/z.R"))
  writeLines(z, fileConn)
  close(fileConn)
  holepunch::write_install(path = x)
  file_path <- glue("{x}/.binder/install.R")
  expect_true(fs::file_exists(file_path))
  fs::dir_delete(x)
})
